import { ProgrammingLanguage } from "../models";

export const convertProgrammingLanguageToDisplayName: Record<
	ProgrammingLanguage,
	string
> = {
	[ProgrammingLanguage.JAVASCRIPT]: "JavaScript",
	[ProgrammingLanguage.TYPESCRIPT]: "TypeScript",
	[ProgrammingLanguage.PYTHON]: "Python",
	[ProgrammingLanguage.RUBY]: "Ruby",
	[ProgrammingLanguage.JAVA]: "Java",
	[ProgrammingLanguage.GO]: "Go",
	[ProgrammingLanguage.C]: "C",
	[ProgrammingLanguage.CPP]: "C++",
	[ProgrammingLanguage.CSHARP]: "C#",
	[ProgrammingLanguage.SWIFT]: "Swift",
	[ProgrammingLanguage.RUST]: "Rust",
	[ProgrammingLanguage.KOTLIN]: "Kotlin",
	[ProgrammingLanguage.PHP]: "PHP",
	[ProgrammingLanguage.SCALA]: "Scala",
	[ProgrammingLanguage.CLOJURE]: "Clojure",
	[ProgrammingLanguage.HASKELL]: "Haskell",
	[ProgrammingLanguage.ERLANG]: "Erlang",
	[ProgrammingLanguage.ELIXIR]: "Elixir",
	[ProgrammingLanguage.PERL]: "Perl",
	[ProgrammingLanguage.GROOVY]: "Groovy",
	[ProgrammingLanguage.BASH]: "Bash",
	[ProgrammingLanguage.R]: "R",
	[ProgrammingLanguage.MATLAB]: "MATLAB",
	[ProgrammingLanguage.OBJECTIVE_C]: "Objective-C",
	[ProgrammingLanguage.ASSEMBLY]: "Assembly",
	[ProgrammingLanguage.LISP]: "Lisp",
	[ProgrammingLanguage.LUA]: "Lua",
	[ProgrammingLanguage.DART]: "Dart",
	[ProgrammingLanguage.COFFEE]: "CoffeeScript",
	[ProgrammingLanguage.SCSS]: "SCSS",
	[ProgrammingLanguage.LESS]: "LESS",
	[ProgrammingLanguage.STYLUS]: "Stylus",
	[ProgrammingLanguage.SASS]: "Sass",
	[ProgrammingLanguage.MARKDOWN]: "Markdown",
	[ProgrammingLanguage.HTML]: "HTML",
	[ProgrammingLanguage.CSS]: "CSS",
	[ProgrammingLanguage.XML]: "XML",
	[ProgrammingLanguage.JSON]: "JSON",
	[ProgrammingLanguage.YAML]: "YAML",
	[ProgrammingLanguage.TOML]: "TOML",
	[ProgrammingLanguage.SQL]: "SQL",
};
