export enum NotificationType {
	ISSUE_COMMENT = "ISSUE_COMMENT",
	PULL_REQUEST_COMMENT = "PULL_REQUEST_COMMENT",
	PULL_REQUEST_REVIEW = "PULL_REQUEST_REVIEW",
	PULL_REQUEST_REVIEW_COMMENT = "PULL_REQUEST_REVIEW_COMMENT",
	MENTION = "MENTION",
	REPOSITORY_WATCH = "REPOSITORY_WATCH",
	REPOSITORY_STAR = "REPOSITORY_STAR",
	REPOSITORY_FORK = "REPOSITORY_FORK",
}
