export enum ProgrammingLanguage {
	JAVASCRIPT = "JavaScript",
	TYPESCRIPT = "TypeScript",
	PYTHON = "Python",
	RUBY = "Ruby",
	JAVA = "Java",
	GO = "Go",
	C = "C",
	CPP = "C++",
	CSHARP = "C#",
	SWIFT = "Swift",
	RUST = "Rust",
	KOTLIN = "Kotlin",
	PHP = "PHP",
	SCALA = "Scala",
	CLOJURE = "Clojure",
	HASKELL = "Haskell",
	ERLANG = "Erlang",
	ELIXIR = "Elixir",
	PERL = "Perl",
	GROOVY = "Groovy",
	BASH = "Bash",
	R = "R",
	MATLAB = "MATLAB",
	OBJECTIVE_C = "Objective-C",
	ASSEMBLY = "Assembly",
	LISP = "Lisp",
}
